### ISSUE TITLE
Drop fragments!?

### ISSUE THREAD

**Issue by plajjan** [SnabbDDoS/snabb#8]
Should we just drop fragmented packets? We don't even attempt at reassembly right now and if we did implement a reassembly function it would be a potential target of DDoS itself.

I believe fragments are fairly rare and that during an attack it would be okay to drop them but maybe we should leave it as an option for the user?

**Comment by dlewen** [comment]
Tempting, but not sure, I've seen fragmented SIP/UDP packets that I wouldn't want to drop. On the other hand, its only during attack, so maybe okay.

**Comment by plajjan** [comment]
@dlewen the SIP signalling itself or RTP ?

**Comment by plajjan** [comment]
There is a reassembler app that is part of the lwAFTR that Igalia is writing. We could probably rip that out of it and use the same. I suspect we need to "harden" it though and be a lot more aggressive about throwing away fragments because it will eat memory real fast.

**Comment by dlewen** [comment]
@plajjan The SIP signalling itself, some new calls would be discarded. Its an old broken implementation, I think SIP "should" change to TCP if the packet is to big to fit in a non fragmented UDP packet.

**Comment by plajjan** [comment]
ok, but that's enough to just make an option out of it at least :)
